### ISSUE TITLE
Update to Quartz v3

### ISSUE THREAD

**Issue by chrisalexander** [akkadotnet/Akka.Quartz.Actor#45]
I haven't had a hugely detailed look at it, but upgrading to Quartz 3.0.3 (from 2.6.1) appears to be enough to break this actor. Will have a look if I get time but seems unlikely in the short term.

**Comment by VengaYBanzai** [comment]
For a fast workaround I just changed the workers to run the _scheduler-Methodes synchronously.
This way the whole concept of the actor still works. Nevertheless its not the best solution.

**Comment by NeilC** [comment]
Can confirm that this package with a Quartz package greater than 2.6.2. Error below is with Quartz 3.0.6

`[ERROR][26/07/2018 12:40:24 PM][Thread 0005][akka://test/user/scheduler] Error while creating actor instance of type Akka.Quartz.Actor.QuartzActor with 0 args: ()
Cause: [akka://test/user/scheduler#1010919354]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.TypeLoadException: Error while creating actor instance of type Akka.Quartz.Actor.QuartzActor with 0 args: () ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Quartz.IScheduler Quartz.Impl.StdSchedulerFactory.GetScheduler()'.
   at Akka.Quartz.Actor.QuartzActor..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)`

**Comment by ptjhuang** [comment]
Closed by #47
